[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[env]
PATH="/opt/homebrew/bin:$HOME/.cargo/bin"

[window]
padding = { x = 5, y = 5 }
decorations = "None"
startup_mode = "FullScreen"
option_as_alt = "Both"

[font]
size = 15.0
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Semibold" }
bold_italic = { family = "SFMono Nerd Font", style = "Semibold Italic" }

[mouse]
hide_when_typing = true

[terminal.shell]
program = "tmux"
args = ["new", "-A", "-s", "main"]

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "["
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "]"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002:"
key = ";"
mods = "Command"
